# Generated by Django 3.2.22 on 2023-11-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, default='authors/default-author.png', null=True, upload_to=''),
        ),
    ]
