# Generated by Django 3.2.22 on 2023-11-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_genre_friendly_name'),
        ('reviews', '0003_remove_productreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.book'),
        ),
    ]
