# Generated by Django 3.2.22 on 2023-11-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_book_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
